# geographic data
state: 'Kansas'
county: 'Wyandotte'
community_name: 'Armourdale'

# historical data
census_year: 2020
census_level: 'tract'
usrdb_start_date: "2024-07-23"  # today?
usrdb_future_date: "2099-01-01"  # some date in the future, replaces NaT values
solar_years: [2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]
# solar_years: [2018]

# price data
# retail_price_elec: 0.1129  # from google, $/kWh
retail_price_elec: 0.1534  # from google, $/kWh (bundled, energy+delivery)
delivery_price_elec: 0.0765  # estimated from bills, $/kWh
# https://www.kansasgasservice.com//media/KGS/Tariffs/20-RSS.pdf
retail_price_gas: 2.3485 # $/Mcf, 0.0080126123 $/kWh

# financial options
interest_rate: 0.07  # as a fraction -- 1% would be 0.01, etc.
payback_period: 20  # years

# ATB cost options
atb_year: 2024  # the ATB publication year // DO NOT CHANGE
atb_params:
    core_metric_case: 'Market'  # 'R&D'
    scenario: 'Moderate'  # 'Conservative', 'Advanced'
    # scale: 'Residential'  # 'Utility', 'Commercial'
    maturity: 'Y'  # 'N'
    crpyears: 30  # '20' // the loan duration
    core_metric_variable: 2025  # Any year 2020-2050 // cost year

technology_options:  # From ATB
  - UtilityPV  # for community solar
  - ResPV  # for rooftop solar
  - CommPV  # for school/community center rooftop solar
  - Commercial Battery Storage
  - Utility-Scale Battery Storage
  - Residential Battery Storage

# model options
topology: "sectoral"  # or building type // NOT IMPLEMENTED

# building data options
building_data_options:
  resstock_year: 2021  # DO NOT CHANGE
  comstock_year: 2021  # DO NOT CHANGE
  weather_version: "tmy3"  # or "amy2018"
  release_version: 1
  building_types:
    residential:
      - multi-family_with_2_-_4_units
      - multi-family_with_5plus_units
      - single-family_attached
      - single-family_detached
      - mobile_home
    # commercial: # pending implementation
    #   -

energy_sectors:
  - residential
  # - commercial  # pending implementation

# geographic options
geographic_crs: 4326  # for using lat/lon; EPSG code
projected_crs: 5070  # for doing calculations; EPSG code

# solver options
solver: 'CPLEX'

# sensitivity options