# geographic data
state: 'Kansas'
county: 'Wyandotte'
community_name: 'Armourdale'

# historical data
census_year: 2020
census_level: 'tract'
usrdb_start_date: "2024-07-23"  # today?
usrdb_future_date: "2099-01-01"  # some date in the future, replaces NaT values

# price data
retail_price_elec: 0.1129  # from google, $/kWh
# https://www.kansasgasservice.com//media/KGS/Tariffs/20-RSS.pdf
retail_price_gas: 2.3485 # $/Mcf, 0.0080126123 $/kWh

# model options
topology: "sectoral"  # or building type?

# building data options
building_data_options:
  resstock_year: 2021  # DO NOT CHANGE
  comstock_year: 2021  # DO NOT CHANGE
  weather_version: "tmy3"  # or "amy2018"
  release_version: 1
  building_types:
    residential:
      - multi-family_with_2_-_4_units
      - multi-family_with_5plus_units
      - single-family_attached
      - single-family_detached
      - mobile_home
    # commercial: # pending implementation
    #   -

energy_sectors:
  - residential
  # - commercial  # pending implementation


# geographic options
geographic_crs: 4326  # for using lat/lon; EPSG code
projected_crs: 5070  # for doing calculations; EPSG code
